apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: techcommerce
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/techcommerce"
  API_KEY: "your-api-key-here"
  JWT_SECRET: "your-jwt-secret-here"
  ENCRYPTION_KEY: "your-encryption-key-here"
