apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: techcommerce
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  sessionAffinity: None
