apiVersion: v1
kind: Service
metadata:
  name: product-api
  namespace: techcommerce
  labels:
    app: product-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: product-api
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  sessionAffinity: None
